### ISSUE TITLE
get exact latitude and longitude values using the get_bygeom function

### ISSUE THREAD

**Issue by JJguri** [cheginit/pydaymet#14]
I want to compare data from daymet with NASA power data (0.5-degree resolution). To do that I need to download exact lat/long combinations from daymet to be aggregated. My polygon of download should be:
`extend = (-87.75, 38.25, -86.25, 39.75)`. Then I am applying a function to aggregate data to 0.5-degree resolution, for example, all lats from daymet between 38 and 38.5 should be classified as 38.25 to be compared with NASA power data. The problem is that when I use the following code:

```
extend = (-87.75, 38.25, -86.25, 39.75)
for yr in range(1980, 2010):
    daymet.get_bygeom(extend, yr, variables=["srad","tmin","tmax","prcp"]).to_netcdf(
        r'C:\...\data\test\daymet\final\{}.nc'.format(yr)
    )
```

I am getting lat values from 38.0731 to 39.9131 as is showed in the figure:

![Untitled](https://user-images.githubusercontent.com/41041705/119586504-2ede3200-be10-11eb-94ea-f98e4c3e25f8.jpg)

I would like to get lat values only from 38 to 40 degrees exactly. How can I do that?

**Describe the solution you'd like**
I do not know.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by cheginit** [comment]
The issue is that Daymet's projection is Lambert Conformal Conic and if you're trying to compare it with a data in another projection you need to reproject your data. You might want to give [rioxarray](https://corteva.github.io/rioxarray/stable/examples/examples.html) a try. Perhaps, reproject by matching or resampling is what you're interested.

**Comment by JJguri** [comment]
Hi @cheginit thanks for your comment. I will have a look to rioxarray.

**Comment by cheginit** [comment]
Did using `rioxarray` address your issue?

**Comment by JJguri** [comment]
I did not use it yet. we are not using the data right now so I will create new issues if required in the future. Feel free to close it. Thanks

**Comment by cheginit** [comment]
Sure!
