### ISSUE TITLE
solar radiation data unit and values

### ISSUE THREAD

**Issue by JJguri** [cheginit/pydaymet#15]
**Is your feature request related to a problem? Please describe.**
I am comparing solar radiation data from daymet vs AgMERRA and NASAPOWER. Accordingly with the metadata, solar radiation data from daymet is in W/m2 and the definition is: incident shortwave radiation flux density in watts per square meter, taken as an average over the daylight period of the day. NOTE: Daily total radiation (MJ/m2/day) can be calculated as follows: ((srad (W/m2) * dayl (s/day)) / l,000,000). I converted it to MJ m-2 to be compared with the other two sources. However, after conversion, I can see an overestimation of solar radiation (almost double) in daymet vs the other sources, please see below:

![Untitled](https://user-images.githubusercontent.com/41041705/119794720-1e66ae00-bf1b-11eb-9ec5-5c2dfd963560.jpg)
Here you can see the cumulative solar radiation between May and October from daymet, agmerra and nasapower. First panel is daymet vs agmerra, second daymet vs nasapower and third nasapower vs agmerra.

I am not sure if I am comparing oranges with oranges. Seems to be that something happen with daymet data, due to the other two sources match well. Could be the data aggregation issue? others?

The raw data from the nc file  is as follows (1984-2010 for this extend = (-87.75, 38.25, -86.25, 39.75)):

* for agmerra dataset from 3 to 371 W/m2.
* for daymet dataset 26 to 576 W/m2.

**Describe the solution you'd like**
none

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by cheginit** [comment]
I compute the radiation with the same method, ``r_surf = clm_ds["srad"] * clm_ds["dayl"] * 1e-6``, for calculating PET. I validated the PET with CAMELS' and they were pretty close. I haven't used those databases that you mentioned so maybe there are some details that you're missing. If you are sure about that maybe you can contact the developers of Daymet and ask about it.

**Comment by JJguri** [comment]
thanks @cheginit, I will have a look in detail to figure out if I am missing something. Otherwise, I will contact the data developers.

**Comment by JJguri** [comment]
> I compute the radiation with the same method, `r_surf = clm_ds["srad"] * clm_ds["dayl"] * 1e-6`, for calculating PET. I validated the PET with CAMELS' and they were pretty close. I haven't used those databases that you mentioned so maybe there are some details that you're missing. If you are sure about that maybe you can contact the developers of Daymet and ask about it.

can you please share a map or range of dayl values for some region? thanks

**Comment by cheginit** [comment]
Sure.
![image](https://user-images.githubusercontent.com/13016644/119923732-dace6d00-bf37-11eb-8d66-dea4dadf5152.png)

**Comment by JJguri** [comment]
thanks @cheginit. I am just wondering how you can set up the dark background in Jupyter??

**Comment by cheginit** [comment]
I am using Jupyter Lab's Dark theme:
![image](https://user-images.githubusercontent.com/13016644/120214112-a1c51f80-c1f9-11eb-941a-36899146bca5.png)

**Comment by cheginit** [comment]
Have you figured out the reason for this discrepancy among the data?

**Comment by JJguri** [comment]
yes. I was considering the factor 86400 to convert instead to use the dayl variable.

**Comment by cheginit** [comment]
Great, glad it's resolved.
