### ISSUE TITLE
Ability to ignore check certificate

### ISSUE THREAD

**Issue by HalfEatenPie** [cheginit/pydaymet#41]
**Is your feature request related to a problem? Please describe.**
get_by* functions are pulling from a remote server that uses SSL for encryption.  These servers can sometimes have an expired SSL certificate which ends up failing the entire function.  While SSL encryption is important, sometimes it's a barrier to access the dataset during time crunches.  

**Describe the solution you'd like**
An option (by default disabled, but an option nevertheless) to ignore checking the certificate would be appreciated.  (e.g. `wget --no-check-certificate`).  The function seems to be using https://github.com/cheginit/async_retriever, so further modifications may be needed to pass-through these changes.  

**Describe alternatives you've considered**
Downloading the full dataset locally on our computing cluster then working on it locally.  This increases our computing operations cost, storage costs, and time cost (as we create a local copy of the dataset).  

Thank you very much for creating this package and being so helpful.  This is a feature request.

**Comment by cheginit** [comment]
Your feature request makes sense. I exposed the `ssl` argument of `aiohttp`. Until I release new official versions, you can install both `async_retriever` and `pydaymet` from their respective repositories like so:

```bash
pip install git+https://github.com/cheginit/pydaymet
pip install git+https://github.com/cheginit/async_retriever
```

Then you can pass `ssl=False` to `get_by*` functions or `--disable_ssl` to PyDaymet's CLI to disable the check.

**Comment by HalfEatenPie** [comment]
Thanks for the quick turnaround!  Your resolution works perfectly and looking forward to this feature being included in the next release.

**Comment by cheginit** [comment]
Great!
