### ISSUE TITLE
daymet.get_bygeom() missing dates, dec 31st on leap years

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [cheginit/pydaymet#45]
Hello, hope you are having a safe and reasonable time during this omicron debacle. As the title says, I'm pulling daymet data over 2001 to 2020 but noticed I was missing values when I tried to join it with streamflow data. When I compared the date output of daymet with a date index I noticed it was missing the 31st of december on every leap year. Any thoughts on how to get these days to come through in the pull?

```
from pynhd import NLDI
import pydaymet as daymet
import pandas as pd

geometry = NLDI().get_basins("08245000").geometry[0]
dates = ('2001-01-01', '2020-12-31')
var = ['dayl','prcp','srad','swe', 'tmax','vp']   
daily = daymet.get_bygeom(geometry, dates, variables=var, pet="hargreaves_samani")

pd.date_range(start = '2001-01-01T12:00:00.000000000', end = '2020-12-31T12:00:00.000000000' ).difference(daily.time.values)

```
Output:
DatetimeIndex(['2004-12-31 12:00:00', '2008-12-31 12:00:00',
               '2012-12-31 12:00:00', '2016-12-31 12:00:00',
               '2020-12-31 12:00:00'],
              dtype='datetime64[ns]', freq=None)

**Comment by cheginit** [comment]
Hi Flash! Thanks, you too.

Daymet database doesn't consider leap years. So all years have the same number of days. You read about the assumptions and their methodology on their [website](https://daymet.ornl.gov/overview).

I usually handle this issue by using the dates from the climate dataset to slice the streamflow dataframe like this:

**Comment by cheginit** [comment]
Although, a more robust approach would be to use [index intersection](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.intersection.html) instead of using `.loc` alone.

**Comment by Flash-Of-Thunder** [comment]
Interesting...this very helpful. Many thanks!!
