### ISSUE TITLE
Daymet download slows to a crawl randomly and frequently

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [cheginit/pydaymet#47]
Hello, this is likely out of your control but I'm curious if someone here has thoughts on this. I checked out a few of the other posts but didn't see this exact framing...let me know if this is actually already been answered. 

I'm assuming the daymet server hosting the information gets back-logged or my priority is reduced because I've been having outlandish download times. I don't really understand. I wrote a quick script to show how the download speed slows to a crawl:

```
from pynhd import NLD
import pydaymet as daymet
import time
```

```
for year in range(1,40):
    start_time = time.time() 
    dates = ('1980-01-01', f'{str(year+1980)}-01-01')
    #small basin of 110 km^2
    geometry = NLDI().get_basins("08245000").geometry[0]
    daily = daymet.get_bygeom(geometry, dates, pet="hargreaves_samani", ssl=False)
    print(f"-----{year} year took {(time.time()-start_time)} seconds------")
```

output:

-----1 year took 0.6903493404388428 seconds------
-----2 year took 0.8716373443603516 seconds------
-----3 year took 1.028099536895752 seconds------
-----4 year took 1.210374355316162 seconds------
-----5 year took 227.60904359817505 seconds------
-----6 year took 234.76095414161682 seconds------
-----7 year took 240.56864047050476 seconds------
-----8 year took 273.4590497016907 seconds------

Sometimes it just stops and never gets the 'daily' value.

The goal is to download ~310 robust gages in California for 1980-2020. But with this current issue it seems impossible with this approach.

**Comment by cheginit** [comment]
Yes, that's my experience as well. Other than server time, there might be some system performance effects as well. What I usually do for long time periods is to download the data for a year (or a couple of years) at a time and save it to disk. You can just write  for loop with year as the iterator. You can take a look at issue #13 that includes my proposed code for handling long term requests.

**Comment by Flash-Of-Thunder** [comment]
I see, I see. Yes I think this will work well. Thanks!
